# Generated by Selenium IDE
# import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import urllib.request
from selenium.webdriver.firefox.options import Options as FirefoxOptions


# options = FirefoxOptions()
# options.add_argument("--headless")

driver = webdriver.Firefox()
vars = {}



    # driver.quit()
  
def test_untitled():
  
  driver.get("https://www.xvideos.com/")
  driver.set_window_size(1920, 1012)
  element = driver.find_element(By.CSS_SELECTOR, ".icf-cog:nth-child(2)")
  actions = ActionChains(driver)
  actions.move_to_element(element).perform()
  driver.find_element(By.CSS_SELECTOR, ".icf-cog:nth-child(2)").click()
  element = driver.find_element(By.CSS_SELECTOR, "body")
  # actions = ActionChains(driver)

  actions = ActionChains(driver)
  actions.move_to_element(element).perform()
  element = driver.find_element(By.CSS_SELECTOR, "body")
  actions = ActionChains(driver)
  driver.find_element(By.LINK_TEXT, "Log in").click()
  time.sleep(10)
  driver.find_element(By.CSS_SELECTOR, "#signin-form-block > fieldset").click()
  driver.find_element(By.ID, "signin-form_login").click()
  driver.find_element(By.ID, "signin-form_password").send_keys("Facebookme1")
  driver.find_element(By.ID, "signin-form_login").send_keys("ngecu16@gmail.com")
  driver.find_element(By.CSS_SELECTOR, ".col-sm-offset-4 > .btn-danger:nth-child(1)").click()

 
  elems = driver.find_elements_by_tag_name('a')
  numbers = ['1','2','3','4','5','6','7','8','9']
  for idx,elem in enumerate(elems):
    href = elem.get_attribute('href')
    if href is not None:
      if 'video' in href and len(href) > 61:
        for x in numbers:
          if x in href:
            try:
              urllib.request.urlretrieve(href, '/home/ngecu/Downloads/{}.mp4'.format(idx))
              print("downloading:{} ".format(href))
            except :
              print("skipped")

      

  # elems = driver.find_element_by_css_selector(".thumb")
  # elems.click()
  # elems = driver.find_elements_by_xpath("//a[@href]")
  # links = driver.find_elements_by_partial_link_text('video')


  # elems = driver.find_element_by_partial_link_text("pic")
  # for el in elems:
    # print("el:",el)
    # links = el.find_elements_by_tag_name("a")
    # for link in links:
    #   print(link.get_attribute(href))
    # el.click()
    # driver.find_element(By.CSS_SELECTOR, ".right > img:nth-child(2)").click()
    # driver.execute_script("window.scrollTo(0,466)")
    # element = driver.find_element(By.CSS_SELECTOR, "body")
    # actions = ActionChains(driver)
    # actions.move_to_element(element, 0, 0).perform()
    # driver.find_element(By.CSS_SELECTOR, "a:nth-child(1) > strong").click()

  # driver.find_element(By.CSS_SELECTOR, ".icf-cog:nth-child(2)").click()
  # driver.find_element(By.ID, "mobile-login-btn").click()
  # driver.find_element(By.LINK_TEXT, "Log out").click()
  driver.close()


test_untitled()