# Generated by Selenium IDE
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time
from selenium.webdriver.firefox.options import Options

options = Options()
options.headless = True
driver = webdriver.Firefox()

category_links = []

def Categories():

    driver.get("https://scartek.co.ke/")
    # driver.set_window_size(1920, 1012)    
    categories = driver.find_elements_by_css_selector("li[class^='menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-has-children']>a")
    print("connection established")
    # sub_categories = driver.find_elements_by_css_selector("li[class^='menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item']>a")

    # f = open("category_links.txt", "w")
    # f.write("\n" + "CATEGORIES + LINKS" + "\n" )
    # for h in categories:
    #     f.write(h.get_attribute("href") + "," + "\n" )       
    # driver.find_element(By.CSS_SELECTOR, ".departments-menu-title > span").click()
    # time.sleep(5)

    # f.write("\n" + "CATEGORIES & SUB CATEGORIES + LINKS" + "\n" )
    print("Categories found")

    for item in categories:
        # Products(str(item.get_attribute("href")))
        category_links.append(str(item.get_attribute("href")))
        # print(item.get_attribute("innerHTML") + " - " + item.get_attribute("href") )
        # f.write(item.get_attribute("innerHTML") + " - " + item.get_attribute("href") + "," + "\n")
    
    # f.close()
    driver.close()



def Products(link):
    driver.get(str(link))
    # driver.set_window_size(1920, 1012)    
    products = driver.find_elements_by_css_selector("li[class^='product type-product']")
    # sub_categories =driver.find_elements_by_css_selector("li[class^='menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item']>a")

    # f = open("bluetooth.txt", "w")
    # f.write("\n" + "BLUETOOTH PRODUCTS" + "\n" )
    print("Products found")

    for product in products:
        product_links = product.find_elements_by_css_selector("a[class^='woocommerce-LoopProduct-link woocommerce-loop-product__link']")
        product_titles = product.find_elements_by_css_selector("h2[class^='woocommerce-loop-product__title']")
        product_images = product.find_elements_by_css_selector("img[class^='attachment-woocommerce_thumbnail size-woocommerce_thumbnail']")
        product_price  = product.find_elements_by_css_selector("span[class^='price']")

        for title in product_titles:
            print(" product title : ",title.get_attribute("innerHTML"))        
            
            for link in product_links:
                print("link : ", link.get_attribute("href"))
                # Items(link.get_attribute("href"))

                # for image in product_images:
                #     print("image source : ",image.get_attribute("src"))
                    
                #     for price in product_price:
                #         prices = price.find_elements_by_css_selector("span[class^='woocommerce-Price-amount amount']")
                #         print(prices[0].text)
                      

                        # for price in prices:
                        #     print("price is {}".format(price.text))
                        




        # f.write(h + "," + "\n" )       
    # driver.find_element(By.CSS_SELECTOR, ".departments-menu-title > span").click()
    # time.sleep(5)

    # f.write("\n" + "SUB CATEGORIES" + "\n" )

    # for item in sub_categories:
    #     print(item.get_attribute("innerHTML"))
    #     f.write(item.get_attribute("innerHTML") + "," + "\n")
    
    driver.close()


def Items(link):
    driver.get(link)
    item_title = driver.find_element_by_css_selector("h1[class^='product_title entry-title']")
    item_price = driver.find_element_by_css_selector("span[class^='woocommerce-Price-amount amount']")
    summary_label = driver.find_element_by_css_selector("h3[class^='summary-label']") 
    short_description = driver.find_element_by_css_selector('.woocommerce-product-details__short-description h3')
    lists = driver.find_elements_by_css_selector('.woocommerce-product-details__short-description li')
    for l in lists:
        print(l.text)

    
    driver.close()
    

    
try:
    # Categories()
  
    # for link in category_links:
    #     time.sleep(5)
    #     Products(link)
    # for link in category_links:
    #     control_string = "window.open('{0}')".format(link)
    #     driver.execute_script(control_string)

    driverversion = driver.capabilities['moz:geckodriverVersion']
    browserversion = driver.capabilities['browserVersion']
    print("druver vaersion ",driverversion)
    print("browser vaersion ",browserversion)
    print("selenium version ",selenium.__version__)

except :
    driver.close()
    print("error")


