# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSad():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_sad(self):
    self.driver.get("https://liveauction1.cash/login")
    self.driver.set_window_size(1235, 703)
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "password").send_keys("Facebookme1@gmail.com")
    self.driver.find_element(By.ID, "email").send_keys("ngecu16@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".vlt-btn__text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".kt-menu__item:nth-child(2) .kt-menu__link-text").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".kt-menu__item:nth-child(2) > .kt-menu__link")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".kt-portlet:nth-child(4) .form-control").click()
    self.driver.find_element(By.CSS_SELECTOR, ".kt-portlet:nth-child(4) .form-control").send_keys("1200")
    self.driver.find_element(By.CSS_SELECTOR, ".kt-portlet:nth-child(4) .btn").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".kt-menu__item:nth-child(4) .kt-menu__link-text").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".kt-menu__item:nth-child(1) .kt-menu__link-text")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".kt-menu__item:nth-child(1) .kt-menu__link-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".kt-grid--stretch:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".kt-portlet:nth-child(4) .form-control").click()
    self.driver.find_element(By.CSS_SELECTOR, ".kt-portlet:nth-child(4) .form-control").send_keys("1200")
    self.driver.find_element(By.CSS_SELECTOR, ".kt-portlet:nth-child(4) .btn").click()
    self.driver.close()
    self.vars["first"] = self.driver.find_element(By.CSS_SELECTOR, ".kt-widget17__items:nth-child(4) > .kt-widget17__item:nth-child(2) > .kt-widget17__desc").text
    self.vars["second"] = self.driver.find_element(By.CSS_SELECTOR, ".kt-widget17__items:nth-child(1) > .kt-widget17__item:nth-child(2) > .kt-widget17__desc").text
  
