# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAsd():
  def setup_method(self, method):
    driver = webdriver.Firefox()
    vars = {}
  
  def teardown_method(self, method):
    driver.quit()
  
  def test_asd(self):
    driver.get("https://liveauction1.cash/login")
    driver.set_window_size(1920, 1012)
    driver.find_element(By.ID, "email").click()
    driver.find_element(By.ID, "password").send_keys("Facebookme1@gmail.com")
    driver.find_element(By.ID, "email").send_keys("ngecu16@gmail.com")
    driver.find_element(By.CSS_SELECTOR, ".vlt-btn").click()
    driver.find_element(By.CSS_SELECTOR, ".vlt-btn").click()
    driver.find_element(By.CSS_SELECTOR, ".kt-menu__item:nth-child(2) .kt-menu__link-text").click()
    driver.find_element(By.CSS_SELECTOR, ".kt-menu__item:nth-child(2) .kt-menu__link-text").click()
    element = driver.find_element(By.CSS_SELECTOR, ".kt-menu__item:nth-child(3) > .kt-menu__link")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    driver.find_element(By.NAME, "amount").send_keys("1200")
    driver.find_element(By.CSS_SELECTOR, ".kt-portlet:nth-child(4) .form-control").click()
    driver.find_element(By.CSS_SELECTOR, ".kt-portlet:nth-child(4) .form-control").send_keys("1200")
    driver.find_element(By.CSS_SELECTOR, ".kt-portlet:nth-child(4) .btn").click()
    driver.find_element(By.CSS_SELECTOR, ".kt-widget17__items:nth-child(1) > .kt-widget17__item:nth-child(2) > .kt-widget17__desc").click()
    vars["expenses"] = driver.find_element(By.CSS_SELECTOR, ".kt-widget17__items:nth-child(1) > .kt-widget17__item:nth-child(2) > .kt-widget17__desc").text
  
