# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCat():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cat(self):
    self.driver.get("http://127.0.0.1:8000/admin/")
    self.driver.set_window_size(1235, 698)
    self.driver.find_element(By.ID, "header").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4)").click()
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("ngecu")
    self.driver.find_element(By.ID, "id_password").send_keys("d")
    self.driver.find_element(By.CSS_SELECTOR, ".submit-row > input").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".model-customer .addlink")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.LINK_TEXT, "Categorys").click()
    self.driver.find_element(By.CSS_SELECTOR, "li > .addlink").click()
    self.driver.find_element(By.ID, "id_name").send_keys("su")
    self.driver.find_element(By.ID, "id_name").send_keys(Keys.DOWN)
    self.driver.find_element(By.ID, "id_name").send_keys(Keys.DOWN)
    self.driver.find_element(By.ID, "id_name").send_keys("Household supplies")
    self.driver.find_element(By.ID, "id_description").click()
    self.driver.find_element(By.ID, "id_description").send_keys("yu")
    self.driver.find_element(By.ID, "id_icon").send_keys("icon")
    self.driver.find_element(By.ID, "id_tags").send_keys("how tag")
    self.driver.find_element(By.NAME, "_save").click()
    self.driver.find_element(By.CSS_SELECTOR, "li > .addlink").click()
    self.driver.find_element(By.ID, "id_name").click()
    self.driver.find_element(By.ID, "id_name").send_keys("kogo")
    self.driver.find_element(By.ID, "id_description").send_keys("desc")
    self.driver.find_element(By.ID, "id_icon").send_keys("iov")
    self.driver.find_element(By.ID, "id_tags").send_keys("tr")
    self.driver.find_element(By.NAME, "_save").click()
  
