# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestScartexlogin():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_scartexlogin(self):
    self.driver.get("https://scartek.co.ke/")
    self.driver.set_window_size(1920, 1012)
    element = self.driver.find_element(By.LINK_TEXT, "Register or Sign in")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "content").click()
    self.driver.find_element(By.CSS_SELECTOR, ".slick-track > .product:nth-child(7) .attachment-woocommerce_thumbnail:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".departments-menu-title > span").click()
    self.driver.find_element(By.LINK_TEXT, "Accessories").click()
    self.driver.find_element(By.LINK_TEXT, "Accessories").click()
  
