# Generated by Selenium IDE

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys


def How():
    driver = webdriver.Firefox()
    driver.get("https://liveauction1.cash/login")
    driver.set_window_size(1920, 1012)
    driver.find_element(By.ID, "email").click()
    driver.find_element(By.ID, "password").send_keys("Facebookme1@gmail.com")
    driver.find_element(By.ID, "email").send_keys("ngecu16@gmail.com")
    driver.find_element(By.CSS_SELECTOR, ".vlt-btn").click()
    driver.find_element(By.CSS_SELECTOR, ".kt-menu__item:nth-child(2) .kt-menu__link-text").click()
    element = driver.find_element(By.CSS_SELECTOR, ".kt-menu__item:nth-child(3) > .kt-menu__link")
    x = driver.find_element(By.CSS_SELECTOR, ".kt-widget17__items:nth-child(4) > .kt-widget17__item:nth-child(2) > .kt-widget17__desc").text
    y = driver.find_element(By.CSS_SELECTOR, ".kt-widget17__items:nth-child(1) > .kt-widget17__item:nth-child(2) > .kt-widget17__desc").text
    print(x)
    print(y)
    if int(x)>0:
        actions = ActionChains(driver)
        actions.move_to_element(element).perform()
        driver.find_element(By.NAME, "amount").send_keys("1200")
        driver.find_element(By.CSS_SELECTOR, ".kt-portlet:nth-child(4) .form-control").click()
        driver.find_element(By.CSS_SELECTOR, ".kt-portlet:nth-child(4) .form-control").send_keys("1200")
        driver.find_element(By.CSS_SELECTOR, ".kt-portlet:nth-child(4) .btn").click()
        driver.find_element(By.CSS_SELECTOR, ".kt-widget17__items:nth-child(1) > .kt-widget17__item:nth-child(2) > .kt-widget17__desc").click()
        new_y = driver.find_element(By.CSS_SELECTOR, ".kt-widget17__items:nth-child(1) > .kt-widget17__item:nth-child(2) > .kt-widget17__desc").text
        new_x = driver.find_element(By.CSS_SELECTOR, ".kt-widget17__items:nth-child(4) > .kt-widget17__item:nth-child(2) > .kt-widget17__desc").text
        print("new x:",new_x)
        print("new y:",new_y)

    else:
        driver.close()

How()
